Add property missing shell
Error: nhutpm219/.github/master/.github/parse-variable/action.yml (Line: 15, Col: 7): Required property is missing: shell
Error: nhutpm219/.github/master/.github/parse-variable/action.yml (Line: 20, Col: 7): Required property is missing: shell
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. nhutpm219/.github/master/.github/parse-variable/action.yml (Line: 15, Col: 7): Required property is missing: shell,nhutpm219/.github/master/.github/parse-variable/action.yml (Line: 20, Col: 7): Required property is missing: shell